#!/bin/sh

set -e

atis(){
	curl --silent --data "@non-public/atis-secret" https://atis.informatik.kit.edu/1192.php | sed -n 's,^.*<span>Gesamtes Guthaben</span><span>&lt;/<span class="end-tag">u</span>&gt;</span><span>:</span><span>&lt;/<span class="end-tag">td</span>&gt;</span><span></span><span>&lt;<span class="start-tag">td</span>&gt;</span><span>\([^<]*\)</span>.*$,\1,p'
}

while :; do
	printf "\fATIS-Guthaben\n%s Seiten" "$(atis)"
	sleep 20
done | $XECHO -stdin -independent-lines -padding 15 -linespacing 10 
