#!/bin/bash

set -e

while true; do
	#WEATHER=$(curl "de.wttr.in/karlsruhe?TF1qp")
	WEATHER=$(finger karlsruhe@graph.no)
	printf "\f%s" "$WEATHER"
	sleep 600
done | $XECHO -linespacing 1 -padding 0 -align w
