#!/bin/bash
export LANG="en_US.UTF-8"
export HOME=/home/sd
export RATPOISON=ratpoison
export SHELL=/bin/bash

case "$(hostname)" in
	fsm-hase*)
		export LOCATION="FSM"
		export PRINTER="fsm-pr3"
		export MPD_HOST="fsm-hase"
		export KVV_VIEW_IDS="de:8212:3?;de:8212:2?;de:8212:80?;de:8212:3014?"
		export RPCDCFG="config/rpcd/mathe.conf"
		export WATCHDOG=true
		export HEADS="
			:0
		"
		;;
	fsi-hase*)
		export LOCATION="FSI"
		export PRINTER="fsi-pr2"
		export MPD_HOST="fsi-mpd"
		export KVV_VIEW_IDS="de:8212:3?;de:8212:401?maxInfos=5&"
		export RPCDCFG="config/rpcd/info.conf"
		export WATCHDOG="tooling/info-watchdog"
		export HEADS="
			:0
			:1
		"
		;;
	*)	printf "Unsupported host to start on"
		exit 1
		;;
esac
