#!/bin/bash

DOLPHINCFG="non-public/dolphin/Config/Dolphin.ini"
GAMES="/home/sd/games/ROMs"
CONTROLLERS="/dev/input/virtual"


if [ ! -d "$CONTROLLERS" ]; then
	xecho -no-stdin -bc black -fc red -maxsize 100 "No controllers connected"
	exit 0
fi

CARD=
case "$1" in
	EasyMode)
		CARD=Cards/easy
		;;
	HardMode)
		CARD=Cards/hard
		;;
esac

if [ -z "$CARD" ]; then
	printf "No gamecard given\n"
	exit 1
fi

for slot in A B; do
	sed -i -E "s,^Memcard${slot}Path = (.*)$,Memcard${slot}Path = non-public/dolphin/${CARD}/MemoryCard${slot}.EUR.raw,g" "$DOLPHINCFG"
done

IMG="$GAMES/$2.iso"
if [ ! -f "$IMG" ]; then
	printf "No such ROM\n"
	exit 1
fi

tooling/dolphin-pad-config
tooling/dolphin/Build/Binaries/dolphin-emu-nogui --user=non-public/dolphin "$IMG"
