#!/bin/sh
slot_current(){
	printf "%s" "$(snmpget -v1 -cpublic -OvQ "$PRINTER.fsmi.uni-karlsruhe.de" .1.3.6.1.2.1.43.8.2.1.10.1.$1)"
}

slot_name(){
	#name_en=$(snmpget -v1 -cpublic -OvQ "$PRINTER.fsmi.uni-karlsruhe.de" .1.3.6.1.2.1.43.8.2.1.13.1.$1)
	snmpget -v1 -cpublic -OvQ "$PRINTER.fsmi.uni-karlsruhe.de" .1.3.6.1.2.1.43.8.2.1.18.1.$1 | xargs echo
}

disp_info(){
	snmpget  -v1 -cpublic -OvQ "$PRINTER.fsmi.uni-karlsruhe.de" .1.3.6.1.2.1.43.16.5.1.2.1.1 | tr -d '\n' | xargs echo
}

toner(){
	state=$(snmpget -v1 -cpublic -OvQ "$PRINTER.fsmi.uni-karlsruhe.de" .1.3.6.1.2.1.43.11.1.1.9.1.1)
	if [ "$?" = "1" ]; then
		toner="N/A"
	else
		case $state in
			-3) toner="Broken";;
			10) toner="low";;
			100) toner="OK";;
			*) toner="Unknown ($state)";;
		esac
	fi
	printf "%s" "$toner"
}
